# Generated by Django 4.1.4 on 2022-12-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonLego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=255, verbose_name='Lien')),
                ('prix', models.FloatField(verbose_name='Dernier prix')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.productlego')),
            ],
        ),
    ]
