# Generated by Django 4.1.4 on 2022-12-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_amazonlego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlego',
            name='nb_pieces',
            field=models.IntegerField(null=True),
        ),
    ]
