# Generated by Django 4.1.4 on 2022-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLego',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id du produit')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nom du produit')),
                ('link_lego', models.CharField(max_length=255, null=True, verbose_name='Lien de la boutique Lego')),
                ('nb_pieces', models.IntegerField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('theme', models.CharField(max_length=50, null=True, verbose_name='Thème')),
            ],
        ),
    ]
